inputs:
- parameter: 'DiscountRate'
  function: 'read_dr'
- parameter: 'OperationalLife'
  function: 'read_ol'
- parameter: 'SpecifiedAnnualDemand'
  function: 'read_sad'
others:
- parameter: 'Population'
  function: 'read_pop'
  path: 'other_data/pop_projection_NEWAGE.xlsx'
  sheet: 'MaGe Factors'
  header: 12
results:
- parameter: 'AnnualTechnologyEmission'
  function: 'read_emissions'
- parameter: 'CapitalInvestment'
  function: 'read_investment'
- parameter: 'ProductionByTechnologyAnnual'
  function: 'read_net_imp'
- parameter: 'ProductionByTechnologyAnnual'
  function: 'read_net_imp_det'
- parameter: 'AnnualFixedOperatingCost'
  function: 'filter_op_cost'
- parameter: 'AnnualVariableOperatingCost'
  function: 'filter_op_cost'